name: Continuous Integration

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]

jobs:
    run-tests:
        runs-on: ubuntu-24.04

        strategy:
            fail-fast: false
            matrix:
                php: [ 8.0, 8.1, 8.2 ]
                laravel: [ 8.*, 9.*, 10.* ]
                stability: [ prefer-stable ]
                include:
                    - laravel: 8.*
                      testbench: ^6.23
                    - laravel: 9.*
                      testbench: 7.*
                    - laravel: 10.*
                      testbench: 8.*
                exclude:
                  - php: 8.0
                    laravel: 10.*

        name: PHP ${{ matrix.php }} - L${{ matrix.laravel }}
        env:
            PHP: ${{ matrix.os }}
            COMPOSER_MEMORY_LIMIT: -1
            PHP_VERSION: ${{ matrix.php }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-
                      dependencies-laravel-${{ matrix.laravel }}-php-
                      dependencies-laravel-

            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php }}
                  extensions: xdebug, zip

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Execute tests (Unit and Feature)
              run: vendor/bin/phpunit

            - name: Static analysis with PHPStan
              run: vendor/bin/phpstan analyse

            - name: Coding style PSR12 Check
              run: vendor/bin/phpcs
