name: Continuous Integration

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]

jobs:
    run-tests:
        runs-on: ubuntu-20.04

        strategy:
            fail-fast: false
            matrix:
                php: [ 7.3, 7.4, 8.1 8.0 ]
                laravel: [ 7.*, 8.*, 9.* ]
                stability: [ prefer-stable ]
                include:
                    - laravel: 7.*
                      testbench: ^5.20
                    - laravel: 8.*
                      testbench: ^6.23
                    - laravel: 9.*
                      testbench: 7.*
                exclude:
                    - laravel: 9.*
                      php: 7.4
                    - laravel: 9.*
                      php: 7.3

        name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}
        env:
            PHP: ${{ matrix.os }}
            COMPOSER_MEMORY_LIMIT: -1
            COMPOSER_FLAGS: ${{ matrix.composer_flags }}
            PHP_VERSION: ${{ matrix.php }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-
                      dependencies-laravel-${{ matrix.laravel }}-php-
                      dependencies-laravel-

            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php }}
                  extensions: xdebug, zip

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Execute tests (Unit and Feature)
              run: vendor/bin/phpunit

            - name: Static analysis with PHPStan
              run: vendor/bin/phpstan analyse

            - name: Coding style PSR12 Check
              run: vendor/bin/phpcs
